version: "2.1"
services:
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /home/umbrel/umbrel/app-data/sabnzbd/data/config:/config
      - /home/umbrel/umbrel/data/storage/downloads/complete:/config/Downloads/complete
    ports:
      - 8080:8080
